Feature
DartHeise/WSTask pull request #1
Opened 2022-05-17 21:11 UTC by DartHeise

Файл с информацией о работниках расположен в src/Employees.txt

2022-05-18 07:47 UTC, progressicu requested changes
комменты нужно оставлять на сложные участки кода. Нет смысла писать к каждой строчке, где и так понятно, что происходит

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        File employeesFile = new File(in.nextLine()); // Файл с данными работников
путь до файла нужно было получить из аргументов

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        BufferedReader bufferedReader = new BufferedReader(fileReader);
используй try with resources

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        return employeesInfoList.toArray(new String[0]); // Преобразуем список в массив и возвращаем
а для чего преобразуешь, почему не продолжить работать со списком?

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        Pattern pattern = Pattern.compile(
Паттерн можно создать один раз на программу, а не на каждый вход в метод

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        m.find();
а для чего просто так вызываем? а если бы ничего не нашлось, то дальше была бы ошибка. Так что нужно проверить, что вообще хоть что-то нашлось

2022-05-18 07:47 UTC, progressicu commented on src/Main.java
> +        createPost(UUID.fromString("854ef89d-6c27-4635-926d-894d76a81707"), "Backend");
для чего было создавать этот метод? Если бы не создавал, а просто писал posts.put, то по кол-ву кода было бы даже меньше и точно также понятно.
Лучше стоило бы создать метод createPosts, там положить эти должности. А тут просто вызвать createPosts()

2022-05-18 07:47 UTC, progressicu commented on src/Post.java
> +    private final String postName;
давай просто name. Понятно же что про post тут

2022-05-18 07:51 UTC, progressicu commented
Где валидация обязательности полей?

2022-05-20 06:19 UTC, DartHeise commented
Паттерн указал в качестве глобальной переменной,  путь к файлу передал с помощью аргумента консоли, при чтении файла использовал try with resources, для валидации обязательности полей в методе parse после инициализации класса Employee проверил поля на null/пустую строку/состоящую только из пробелов. Все остальные указанные недочеты также исправил.

2022-05-21 07:29 UTC, progressicu approved these changes

2022-05-21 07:29 UTC, progressicu commented on src/Main.java
> +            throw new Exception("Incorrect file: " + employee);
Всё ок, но давай после этой строки хотя бы пустую вставим, чтобы разделить визуально, где идёт обработка поиска, а где создание работника. Так читать код просто легче, когда куски кода в одном методе разделены пустой строкой

2022-05-21 07:29 UTC, progressicu commented on src/Main.java
> +            throw new Exception("Incorrect file: " + employee);
А почему Incorrect file, если передаешь строку с данными работника?

2022-05-21 08:08 UTC, DartHeise commented on src/Main.java
> +            throw new Exception("Incorrect file: " + employee);
Наверное, тогда лучше "Incorrect string format"

2022-05-21 08:10 UTC, merged