Maven, json, string searching, tests
DartHeise/WSTask pull request #2
Opened 2022-05-26 03:01 UTC by DartHeise

Разделил код на слои (модель, сервис, main), изменил систему сборки на maven, добавил опциональный поиск по строке в качестве консольного аргумента, изменил файл с сотрудниками с txt на json, добавил валидацию параметров Employee, покрыл тестами метод получения сотрудников и их опциональный поиск

2022-05-27 00:32 UTC, snusmum commented on .idea/compiler.xml
> +      </profile>
Нужен .gitignore

2022-05-27 01:35 UTC, snusmum requested changes
Нужно отмечать, какие комменты принимаются, а какие нет.
Если планируешь править, то можно ставить смайлик, напр 👍 
Если не согласен, то писать в коммент возращения.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +    private final String pathName = "C:\\Users\\Иван\\IdeaProjects\\WSTask_Maven\\src\\test\\java\\resources\\Employees.json";
Тесты не работают нигде, кроме твоего компа. Нужно использовать относительные пути.
Сейчас проблему можно решить так
`AddEmployeeActionTest.class.getClassLoader().getResource("Employees.json").getPath()`
Со спрингом придут более удобные методы получения ресурсов.

2022-05-27 01:35 UTC, snusmum commented on src/main/java/action/AddEmployeesAction.java
> +        EmployeeMapperImp employeeMapperImp = new EmployeeMapperImp();
Можно создать один экземпляр в конструкторе и пользоваться им.

2022-05-27 01:35 UTC, snusmum commented on src/main/java/mapper/EmployeeMapperImp.java
> +public class EmployeeMapperImp implements EmployeeMapper {
А почему пришлось создать маппер ркуками? По описанному выше интерфейсу с аннотацией `@Mapper` MapStruct сам создаст всё, что требуется и поместит в папку target.

Для того, чтобы к нему обращаться в коде без подсвечивания ошибки потребуется собрать проект `mvn clean package`

2022-05-27 01:35 UTC, snusmum commented on src/main/java/mapper/EmployeeMapperImp.java
> +public class EmployeeMapperImp implements EmployeeMapper {
Если сборка ломается, то, видимо не хватает блока <build> с нужными препроцессорами

2022-05-27 01:35 UTC, snusmum commented on src/main/java/model/CreateEmployeeArgument.java
> +public class CreateEmployeeArgument {
Для таких аргументов, обычно, поля можно делать финальными. Конструктор скрывать и добавлять билдер.

2022-05-27 01:35 UTC, snusmum commented on src/main/java/model/Employee.java
> +    private final String firstName;
А вот в модели поля чаще делают не финальными, т.к. они могут обновляться

2022-05-27 01:35 UTC, snusmum commented on src/main/java/service/EmployeeService.java
> +    public List<Employee> getAllOrdered(String[] args) throws Exception {
Это стоило распарсить там же, где получался путь до файла и в метод сервиса передать уже свой класс с именованными параметрами для поиска.
Обработка аргументов - не часть логики сервиса для работы с сотрудниками.

2022-05-27 01:35 UTC, snusmum commented on src/main/java/service/EmployeeService.java
> +        Pattern pattern = Pattern.compile("(?<lastName>.+|)_(?<firstName>.+|)/(?<postId>.+|)");
по заданию требовалось передать одну строку и использовать её для по иска по "имени или фамилии"

2022-05-27 01:35 UTC, snusmum commented on src/main/java/service/PostService.java
> +    @Getter
обычно такое наружу не отдают.  Работать можно только через методы, как getPostByUUID ниже

2022-05-27 01:35 UTC, snusmum commented on src/test/java/actionTest/AddEmployeeActionTest.java
> +    private final String pathName = "C:\\Users\\Иван\\IdeaProjects\\WSTask_Maven\\src\\test\\java\\resources\\Employees.json";
По идее это юнит-тест. Поэтому для внешних зависимостей (fileService, PostService, EmployeeService) нужно задать моки (заглушки), которые будут отдавать то, что нужно для проверки логики действия.
Как этого добиться (на выбор):
- использовать библиотеку Mockito
- для сервисов добавить интерфейсы, которые те будут реализовывать. Тогда в тесте можно подставлять кастомные реализации этих интерфейсов, которые будут отдавать то, что требуется.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +    private final String pathName = "C:\\Users\\Иван\\IdeaProjects\\WSTask_Maven\\src\\test\\java\\resources\\Employees.json";
Но опять же. Это юнит-тест. Если и наполнять сервис данными из файла, то делать это нужно без использования других классов, чтобы тестировать логику изолированно.
В данном случае можно руками создать сотрудников и поместить их в сервис.
Другой вариант - как ниже с использованием GetEmployeesFileAction, но нужно учитывать, что мапер на уровне тестов ещё недоступен.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +                .collect(Collectors.toList());
Это относится к блоку Arrange

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +                .collect(Collectors.toList());
В тестах лучше не добавлять лишнюю логику.
У тебя уже есть подготовленный файл с ожидаемыми результатами.
Достаточно прочитать его и вернуть данные в том же порядке.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +        exception = Assertions.assertThrows(Exception.class, () -> employeeService.getAllOrdered(args));
Это Act хоть и с ассеротм :)
Если пользоваться AssertJ, то в подобном методе валидации вторую проверку можно писать в продолжение первой.
В этом случае блок помечают, например // Act & Assert. Код становиться чуть понятнее при первом взгляде.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +    public void SetUp(String consoleArgument) throws Exception {
Названия методов принято с маленькой буквы начинать.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/serviceTest/EmployeeServiceTest.java
> +        SetUp(String.format("%s Ivanov_Ivan/", pathName));
Было бы понятнее, если бы переменная args явно инициализировалась прямо здесь.
И глобальная она не нужна, т.к. в каждом методе своё значение.

Но после выноса парсинга в main здесь уже будет формирование более понятного аргумента поиска.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/resources/GetEmployeesFileAction.java
> +public class GetEmployeesFileAction {
Такое, обычно, размещают в test/utils

2022-05-27 01:35 UTC, snusmum commented on src/test/java/resources/GetEmployeesFileAction.java
> +        EmployeeMapperImp employeeMapperImp = new EmployeeMapperImp();
После перехода на полноценное использование MapStruct этот маппер станет недоступен в тестах (если прогонять мавеном).
В идее после сборки без тестов такой код пройдёт, но это плохой вариант.

2022-05-27 01:35 UTC, snusmum commented on src/test/java/resources/Employees.json
> +[
эти данные должны лежать уровнем выше (/test/resources)
чтобы не захламлять resources принято создавать вложенные папки (напр. jsons). Для больших проектов может добавляться ветвление по тестовым классам, чтобы всё в одной куче не лежало.

2022-05-27 01:41 UTC, snusmum commented on src/main/java/service/EmployeeService.java
> +            stream = stream.filter(x -> x.getLastName().equals(lastName));
Так найдётся только по точному совпадению, включая регистр.
Нужно искать под подстроке без учёта регистра.

2022-05-29 12:25 UTC, snusmum commented on src/main/java/mapper/EmployeeMapperImp.java
> +public class EmployeeMapperImp implements EmployeeMapper {
Другой вариант для работы с автогенерируемыми мапперами - использовать `Mappers.getMapper()`.
Но чтобы им воспользоваться, а в тесте применять моки, маппер нужно будет передавать в конструктор.

2022-06-01 11:53 UTC, DartHeise commented on src/main/java/mapper/EmployeeMapperImp.java
> +public class EmployeeMapperImp implements EmployeeMapper {
Исправил, в тестах добавил класс EmployeeMapperImplementation

2022-06-01 11:54 UTC, DartHeise commented on src/main/java/service/EmployeeService.java
> +    public List<Employee> getAllOrdered(String[] args) throws Exception {
Исправил, передаю в метод класс SearchingParameters

2022-06-01 11:55 UTC, DartHeise commented on src/test/java/actionTest/AddEmployeeActionTest.java
> +    private final String pathName = "C:\\Users\\Иван\\IdeaProjects\\WSTask_Maven\\src\\test\\java\\resources\\Employees.json";
Использовал Mockito

2022-06-02 06:15 UTC, snusmum approved these changes
Есть моменты, которые следует поправить перед слиянием:
- поиск по подстроке, а не по совпадению
- избавиться от тестового маппера
Лучше перед слиянием, но можно и в след. задании:
- запустить тесты в maven
- uuid в аргументе поиска вместо string

2022-06-02 06:15 UTC, snusmum commented on pom.xml
> +            </plugin>
Если не сейчас, то в след. дз нужно обеспечить работу тестов через maven

2022-06-02 06:15 UTC, snusmum commented on src/main/java/model/CreateEmployeeArgument.java
> +    @JsonProperty(value = "firstName")
обычно без таких дополнений работает

2022-06-02 06:15 UTC, snusmum commented on src/main/java/model/SearchingParameters.java
> +    private String postId;
Лучше здесь UUID, чтобы не конвертировать при получении списка. В следующем задании контроллер будет сразу принимать UUID и его можно будет передать без лишних операций.

2022-06-02 06:15 UTC, snusmum commented on src/main/java/service/EmployeeService.java
> +                                || x.getFirstName().equalsIgnoreCase(searchParams.getName()));
Нужно переделать на containsIgnoreCase, чтобы искать по вхождению подстроки.

2022-06-02 06:15 UTC, snusmum commented on src/main/java/service/FileService.java
> +}
Логичнее оставить только метод getFile, который вернёт файл по пути, т.к. рискованно сохранять в глобальной переменной объект.

2022-06-02 06:15 UTC, snusmum commented on src/test/java/actionTest/AddEmployeeActionTest.java
> +        EmployeeMapperImplementation employeeMapper = new EmployeeMapperImplementation();
Возможно я неправильно выразился в прошлом комментарии. В этом нет необходимости.
Гораздо проще передать мок маппера в конструктор, как это сделано для сервисов.

2022-06-02 06:15 UTC, snusmum commented on src/test/java/actionTest/AddEmployeeActionTest.java
> +        expected = GetEmployeesFileAction.getEmployeesFile(pathName);
Обычно в юнит-тестах нет необходимости помещать тестовые данные в отдельный файл.
Тем более опыт показывает, что один общий файл на все тесты может стать источником проблем.

Код не сильно усложнится, но проверка станет понятнее, если из маппера возвращать моки сотрудников и проверять, что именно они добавлены в сервис.

2022-06-02 06:15 UTC, snusmum commented on src/test/java/utils/GetEmployeesFileAction.java
> +    }
Для тестов в json нужно помещать готовые объекты (в данном случае сотрудников с должностями), чтобы просто одной строкой считать из json, а не повторять логику, используемую в приложении.

2022-06-03 10:23 UTC, DartHeise commented on src/main/java/model/CreateEmployeeArgument.java
> +    @JsonProperty(value = "firstName")
Изменил на @Jackonised

2022-06-03 10:24 UTC, DartHeise commented on src/main/java/model/SearchingParameters.java
> +    private String postId;
Исправил

2022-06-03 10:24 UTC, DartHeise commented on src/main/java/service/FileService.java
> +}
Оставил только getFile

2022-06-03 10:26 UTC, DartHeise commented on src/test/java/actionTest/AddEmployeeActionTest.java
> +        EmployeeMapperImplementation employeeMapper = new EmployeeMapperImplementation();
Убрал тестовый маппер, замокал настоящий

2022-06-03 10:26 UTC, DartHeise commented on src/test/java/utils/GetEmployeesFileAction.java
> +    }
Убрал лишнюю для тестов логику

2022-06-03 10:34 UTC, merged