added RestControllers, created ApiExceptionHandler, made IT for controllers
DartHeise/WSTask pull request #3
Opened 2022-06-13 12:08 UTC by DartHeise

2022-06-16 02:40 UTC, mv-shallow requested changes

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/dto/CreateEmployeeArgumentDto.java
> +public class CreateEmployeeArgumentDto {
Некорректное название класса. DTO - Data Transfer Object, используем для маппинга данных в запросе и отправляем в качестве ответа. Argument-классы используются для перехода между слоями внутри сервиса. Здесь надо назвать CreateEmployeeDto

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeDtoMapper.java
> +@Mapper(componentModel = "spring")
У тебя маппер настроен в pom, зачем указываешь компонентную модель?

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeDtoMapper.java
> +    EmployeeDto toEmployeeDto(Employee createEmployeeDto);
(Employee employee)

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/exceptionHandler/ApiExceptionHandler.java
> +    public ResponseEntity<Object> handleException(NotFoundException e) {
Можно возвращать класс ошибки, а статус указывать через аннотацию `@ResponseStatus`

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/exceptionHandler/ApiExceptionHandler.java
> +                ("Incorrect id", HttpStatus.NOT_FOUND);
Почему id некорректный? id может быть правильным, просто запись уже удалили. Нелогичное сообщение, лучше "Запись не найдена". Лучше задавать текст при создании исключения и здесь подставлять его в ответ. Тогда будет, например: "Сотрудник не найден", "Должность не найдена"

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    @GetMapping("/get/{id}")
Намерение получить запись ты уже задал тем, что требуется GET-запрос, поэтому сегмент /get/ лишний

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    @PostMapping("/getAll")
Почему POST-запрос, когда требуется получение?

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    public List<EmployeeDto> getAllEmployees(@RequestBody SearchingParameters searchingParams) {
Если оставить (SearchingParameters searchingParams), то спринг будет мапить параметры запроса в поля класса

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/dto/EmployeeDto.java
> +    private final Post post;
В DTO не должна фигурировать сущность

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/post/mapper/PostDtoMapper.java
> +public interface PostDtoMapper {
А зачем несколько разных мапперов? CreatePostArgumentMapper и PostDtoMapper не пестрят логикой, в каждом по одному методу. Нет смысла разделять их. PostMapper

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/model/employee/Contacts.java
> +@Jacksonized
А для чего?

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/mapper/model/EmployeeMapper.java
> +public interface EmployeeMapper {
Часто достаточно одного маппера для сущности

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/service/employeeService/EmployeeService.java
> +    private final EmployeeMapper employeeMapper = new EmployeeMapperImpl();
Из-за чего создаешь самостоятельно?

2022-06-16 02:40 UTC, mv-shallow commented on src/main/java/com/ws/task/service/employeeService/EmployeeService.java
> +        if (!StringUtils.isBlank(searchParams.getName())) {
фильтрацию в отдельный метод

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +                (new File("src\\test\\java\\com\\ws\\task\\resources\\jsons\\controllerTests\\Employees.json"), CreateEmployeeArgument[].class);
Ресурс через ClassLoader

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        compareEmployeeDtoToModelEmployee(employeeDto, employee);
Должно быть сравнение DTO с DTO. Ожидаемые данные задаются программистом, а не берутся из теста(здесь ты в качестве эталона берешь объект класса Employee, но если произошла непреднамеренная модификация, то она будет и в ответе на запрос, и в "эталоне" - ошибка упущена

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +    private EmployeeService employeeService;
Почему не используешь моки? Есть отдельные тесты на сервис, так что здесь можно замокать его

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +    void post() {
create

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        CreateEmployeeArgumentDto createEmployeeArgDto = CreateEmployeeArgumentDto.builder()
Лучше вынести в json и получать как ресурс

2022-06-16 02:40 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        Assertions.assertThrows(NotFoundException.class, () -> employeeService.get(deletedEmployee.getId()));
Плохая проверка. Здесь не нужно проверять создание исключения. Я догадываюсь, что это для того чтобы убедиться, что оставшаяся запись не является ранее удаленной. Проще - оставить в сервисе одну запись и ее удалить, тогда можно просто убедиться, что после удаления сотрудников нет

2022-06-16 02:41 UTC, mv-shallow commented
Зачем удалил старые тесты? Лучше оставь их и доработай, если какие-то поломались после правок

2022-06-19 05:03 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +    private EmployeeService employeeService;
Как лучше всего мокать поля, которые являются `@Autowired`?

2022-06-19 06:52 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/dto/CreateEmployeeArgumentDto.java
> +public class CreateEmployeeArgumentDto {
Исправил

2022-06-19 06:56 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeDtoMapper.java
> +@Mapper(componentModel = "spring")
Написал в pom `-Amapstruct.defaultComponentModel=spring`, чтобы не указывать в мапперах

2022-06-19 06:57 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeDtoMapper.java
> +    EmployeeDto toEmployeeDto(Employee createEmployeeDto);
Исправил

2022-06-19 07:02 UTC, DartHeise commented on src/main/java/com/ws/task/controller/exceptionHandler/ApiExceptionHandler.java
> +    public ResponseEntity<Object> handleException(NotFoundException e) {
Добавил `@ResponseStatus`, в handleException теперь возвращаю информацию о выброшенной ошибке

2022-06-19 07:05 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    @PostMapping("/getAll")
Исправил на `@GetMapping`

2022-06-19 07:11 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/dto/EmployeeDto.java
> +    private final Post post;
Заменил на postId

2022-06-19 07:12 UTC, DartHeise commented on src/main/java/com/ws/task/controller/post/mapper/PostDtoMapper.java
> +public interface PostDtoMapper {
Оставил только мапперы для контроллера и для модели

2022-06-19 07:18 UTC, DartHeise commented on src/main/java/com/ws/task/model/employee/Contacts.java
> +@Jacksonized
Убрал `@Builder` и `@Jacksonized`

2022-06-19 07:23 UTC, DartHeise commented on src/main/java/com/ws/task/mapper/model/EmployeeMapper.java
> +public interface EmployeeMapper {
Для работников сделал абстрактный класс EmployeeArgument, от которого наследуются классы CreateEmployeeArgument и UpdateEmployeeArgument, чтобы у сущности был один маппер. То же самое повторил с должностями

2022-06-19 07:24 UTC, DartHeise commented on src/main/java/com/ws/task/service/employeeService/EmployeeService.java
> +    private final EmployeeMapper employeeMapper = new EmployeeMapperImpl();
Заменил аннотацией `@RequiredArgsConstructor`

2022-06-19 07:25 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        Assertions.assertThrows(NotFoundException.class, () -> employeeService.get(deletedEmployee.getId()));
Убрал лишнюю проверку

2022-06-26 13:36 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeDtoMapper.java
> +@Mapper(componentModel = "spring")
Об этом и речь. Атрибут уже был задан, а здесь он лишний раз указан

2022-06-26 14:17 UTC, mv-shallow requested changes
Все пакеты должны быть в com/ws/task, а не на одном уровне с com.
Пакеты тестов в целом повторяют структуру рабочего кода, поэтому serviceTests и controllerTests не нужны, достаточно обычных наименований. По родительскому пакету и так понятно, что это тесты. Папки в ресурсах через lowercase, файлы через snake_case

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +    private EmployeeService employeeService;
MockBean или SpyBean. Про SpyBean я писал в беседе

2022-06-26 14:17 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeControllerMapper.java
> +public interface EmployeeControllerMapper {
Просто EmployeeMapper. Мапперы обычно располагаем здесь, т.е. для сущности в целом будет один маппер. Редко требуется несколько разных мапперов, но даже в таком случае их располагают в одном пакете

2022-06-26 14:17 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/exceptionHandler/ApiExceptionHandler.java
> +    public String handleException(NotFoundException e) {
Советую добавить класс ErrorDto, пускай пока с одним полем. Если бы у проекта был фронтенд, то при изменении  полей класс легче поддерживать. Да и ошибка редко ограничивается одним сообщением

2022-06-26 14:17 UTC, mv-shallow commented on src/main/java/com/ws/task/controller/post/PostController.java
> +    @PutMapping("/update/{id}")
Общую часть (id) лучше указывать до частной (update)

2022-06-26 14:17 UTC, mv-shallow commented on src/main/java/com/ws/task/service/employeeService/arguments/EmployeeArgument.java
> +    private final String firstName;
Можно использовать Value из lombok

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        EmployeeDto createdEmployee = employeeControllerMapper.toEmployeeDto
Не совсем так. Нужно полностью самому создать EmployeeDto. Файл с ним можно назвать create__expected.json

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +                                                  .uri(uriBuilder -> uriBuilder.path("employee/" + employee.getId().toString())
есть другая форма: uri("employee/{id}",id)

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +                                                  .uri(uriBuilder -> uriBuilder.path("employee/" + employee.getId().toString())
id надо задать явно, в отдельной строке. Не надо получать его из employee

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        EmployeeDto expectedEmployeeDto = expectedEmployeeDtos.get(0);
Это не относится к блоку Arrange, т.к. не является условием для успешной отправки запроса

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        SearchingParameters searchParams = new SearchingParameters();
Для чего? Можно сразу прописывать. Тем более там этих параметров нет, как я понял. Т.е. getAll вызывается как бы без параметров

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        employees = new ObjectMapper().readValue
Почему везде создается новый маппер? Лучше объявить его полем класса и получить с помощью Autowired

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +                (getClass().getClassLoader().getResource("jsons\\controllerTests\\employee\\expectedEmployeeDtos.json"),
файлы через snake_case

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        UUID updatedId = employees.get(0).getId();
Аналогично get

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/PostControllerIT.java
> +        Assertions.assertEquals(response.size(), 3);
Лучше через https://javadoc.io/doc/org.assertj/assertj-core/3.13.2/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension.html
SoftAssertions позволит проверить всё, а не заканчивать на первом несовпадении

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/controllerTest/PostControllerIT.java
> +                                              .expectBodyList(PostDto.class)
Почему список, если возвращается PostDto?

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +        List<Employee> actual;
Почему объявление отдельной строкой?

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +        employees = new ObjectMapper().readValue
Маппер в поле класса

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +    public void getAllOrderedWithFirstNameAndId() throws Exception {
Для поиска можно сделать параметризованный тест https://www.baeldung.com/parameterized-tests-junit-5

2022-06-26 14:17 UTC, mv-shallow commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +        EmployeeMapper employeeMapper = new EmployeeMapperImpl();
Этот класс вообще слабо относится к самому сервису(мапперы всё же много где используются), так что его можно замокать или вынести в поле.

2022-06-29 04:21 UTC, DartHeise commented on src/main/java/com/ws/task/service/employeeService/arguments/EmployeeArgument.java
> +    private final String firstName;
В таком случае класс нужно сделать не абстрактным

2022-06-29 15:11 UTC, mv-shallow commented on src/main/java/com/ws/task/service/employeeService/arguments/EmployeeArgument.java
> +    private final String firstName;
Можно использовать @NonFinal на уровне класса: https://projectlombok.org/features/Value

2022-06-29 15:28 UTC, mv-shallow commented on src/main/java/com/ws/task/service/employeeService/arguments/EmployeeArgument.java
> +    private final String firstName;
Если не нужны другие "свойства" Value, то поля можно сделать private final с помощью аннотации [@FieldDefaults](https://projectlombok.org/features/experimental/FieldDefaults)

2022-07-01 06:27 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/mapper/EmployeeControllerMapper.java
> +public interface EmployeeControllerMapper {
Оставил только один маппер для каждой сущности

2022-07-01 06:27 UTC, DartHeise commented on src/main/java/com/ws/task/controller/exceptionHandler/ApiExceptionHandler.java
> +    public String handleException(NotFoundException e) {
Добавил

2022-07-01 06:29 UTC, DartHeise commented on src/main/java/com/ws/task/service/employeeService/arguments/EmployeeArgument.java
> +    private final String firstName;
Спасибо! Использовал **@NonFinal**

2022-07-01 06:29 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +                                                  .uri(uriBuilder -> uriBuilder.path("employee/" + employee.getId().toString())
Исправил

2022-07-01 06:31 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        EmployeeDto expectedEmployeeDto = expectedEmployeeDtos.get(0);
Убрал expectedEmployeeDto в Assert, employee оставил для мока

2022-07-01 06:32 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/EmployeeControllerIT.java
> +        employees = new ObjectMapper().readValue
Исправил во всех тестах

2022-07-01 06:33 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/PostControllerIT.java
> +        Assertions.assertEquals(response.size(), 3);
Добавил SoftAssertions там, где больше одной проверки

2022-07-01 06:33 UTC, DartHeise commented on src/test/java/com/ws/task/controllerTest/PostControllerIT.java
> +                                              .expectBodyList(PostDto.class)
Исправил на expectBody

2022-07-01 06:35 UTC, DartHeise commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +    public void getAllOrderedWithFirstNameAndId() throws Exception {
Сделал тесты поиска параметризированными

2022-07-01 06:35 UTC, DartHeise commented on src/test/java/com/ws/task/serviceTest/EmployeeServiceTest.java
> +        EmployeeMapper employeeMapper = new EmployeeMapperImpl();
Вынес в поле

2022-07-01 08:54 UTC, mv-shallow requested changes

2022-07-01 08:54 UTC, mv-shallow commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        employees = objectMapper.readValue
Похожий код много где повторяется в классе, имеет смысл сделать из этого утилитарный метод

2022-07-01 08:54 UTC, mv-shallow commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        softAssertions.assertThat(expectedEmployeeDtos.get(1)).isEqualTo(secondEmployeeDto);
Не будет работать, ты не вызываешь assertAll. Можно добавить расширение https://javadoc.io/doc/org.assertj/assertj-core/3.13.2/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension.html и он будет вызван за тебя, только надо убрать объявление из поля класса и указать SoftAssertions в качестве аргумента метода

2022-07-01 08:54 UTC, mv-shallow commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
>      }
А где проверка, что запись действительно удалена?

2022-07-01 08:54 UTC, mv-shallow commented on src/test/java/com/ws/task/service/EmployeeServiceTest.java
> +    @ParameterizedTest
Видимо мы друг друга не поняли) Параметризованные тесты уменьшают количество кода, а здесь по факту представлены обычные тесты, просто блок Arrange представлен в виде параметра, причем у тебя всего одно значение в каждом случае. Имелось в виду, что будет один параметризованный тест, в который на вход будут поступать разные параметры для поиска,  и может еще тест один на случай, если не получится сделать один тест на все кейсы.

2022-07-02 12:20 UTC, DartHeise commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        employees = objectMapper.readValue
Сделал ReadValueAction

2022-07-02 12:20 UTC, DartHeise commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        softAssertions.assertThat(expectedEmployeeDtos.get(1)).isEqualTo(secondEmployeeDto);
Добавил

2022-07-02 12:22 UTC, DartHeise commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
>      }
Добавил проверку на количество записей и наличие удаленной записи в сервисе

2022-07-03 13:22 UTC, progressicu reviewed
Достаточно хорошо получилось 👍 

Давай правим эти мелочи (главное тесты среди них) и уже сольем это

2022-07-03 13:22 UTC, progressicu commented on pom.xml
> +			<groupId>com.fasterxml.jackson.core</groupId>
это не надо, уже есть в зависимостях от spring-a

2022-07-03 13:22 UTC, progressicu commented on pom.xml
> +			<groupId>javax.validation</groupId>
это не надо, уже есть в зависимостях от spring-a

2022-07-03 13:22 UTC, progressicu commented on pom.xml
> +			<artifactId>springfox-swagger2</artifactId>
почему не стартер?

2022-07-03 13:22 UTC, progressicu commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    private final UpdateEmployeeArgumentAction updateEmployeeArgAction;
Названия это и action-а выше не отражает то что они делают

2022-07-03 13:22 UTC, progressicu commented on src/main/java/com/ws/task/controller/employee/dto/UpdateEmployeeDto.java
> +@Jacksonized
а для чего это?

2022-07-03 13:22 UTC, progressicu commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        when(employeeService.get(employeeId)).thenReturn(employee);
а зачем? В интеграционных тестах ты проверяешь микросервис полностью от и до. Моки идут в крайних случаях (о таких случаях будем говорить дальше на занятиях) и это явно не сейчас.
Так что тут почти все тесты нужно поправить

2022-07-03 14:11 UTC, mv-shallow commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        when(employeeService.get(employeeId)).thenReturn(employee);
@DartHeise , в таком случае есть как минимум два варианта:
1) Сервис внедряется в поле класса, создается отдельный метод в данном классе, в котором через service.create добаляется сотрудник, потом через service.getAllOrdered получаем список сотрудников и берем id первого сотрудника - его и используем в тестах на update/get/... ;
2) Переделать коллекцию сотрудников на бин: Добавить класс AppConfig(конфигурация), в нем в качестве бина создать Map и внедрять ее в сервисе, тогда для тестов можно создать тестовую конфигурацию, в которой эта коллекция будет заполняться вручную.

2022-07-04 06:32 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/dto/UpdateEmployeeDto.java
> +@Jacksonized
@Jacksonized позволяет использовать @Builder для десериализации. Можно заменить эти аннотации с помощью @Setter и сделать поля в классе не final

2022-07-04 10:48 UTC, DartHeise commented on pom.xml
> +			<artifactId>springfox-swagger2</artifactId>
Возникали ошибки при загрузке контекста, исправил

2022-07-04 10:49 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/EmployeeController.java
> +    private final UpdateEmployeeArgumentAction updateEmployeeArgAction;
Исправил на createEmployeeArgumentCreator и updateEmployeeArgumentCreator

2022-07-04 10:49 UTC, DartHeise commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        when(employeeService.get(employeeId)).thenReturn(employee);
Моки убрал, использовал первый вариант

2022-07-04 10:55 UTC, DartHeise commented on src/main/java/com/ws/task/controller/employee/dto/UpdateEmployeeDto.java
> +@Jacksonized
Аннотации убрал, оставил только **Data**

2022-07-05 01:58 UTC, merged

2022-07-07 12:12 UTC, mv-shallow commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        when(employeeService.get(employeeId)).thenReturn(employee);
@DartHeise ты слил до одобрения, в итоге с ошибками. У тебя expected классы отлично считывались из json-а, зачем вернул старый вариант? Я до этого писал, чем он плох. В данном случае у Гены было замечание только к тому, что вместо реального сервиса используется мок.

2022-07-08 04:03 UTC, DartHeise commented on src/test/java/com/ws/task/controller/EmployeeControllerIT.java
> +        when(employeeService.get(employeeId)).thenReturn(employee);
Создал новый ПР для исправления ошибок